#!/usr/bin/with-contenv bash

echo '
******************************************************
******************************************************
*                                                    *
*                                                    *
*          This image has been deprecated            *
*                                                    *
*           Use the multi-arch images at             *
*                                                    *
*               linuxserver/tt-rss                   *
*                                                    *
*    https://hub.docker.com/r/linuxserver/tt-rss     *
*                                                    *
*   https://github.com/linuxserver/docker-tt-rss     *
*                                                    *
*                                                    *
*                                                    *
******************************************************
******************************************************'
